gtk/src/lib.rs
Change button label to say "Reboot and Upgrade".
=> Update button text upon download completion

src/repair/sources.rs
=> fix(repair): Only switch source to old-releases if it exists

data/pop-upgrade.service
=> Replace graphical.target with multi-user.target in Requirements for pop-upgrade.service

src/release/mod.rs, src/release/repos.rs, src/repair/crypttab.rs, src/repair/mod.rs
=> fix(repair): Add plain option to cryptswaps in crypttab

changelogs/20.10, src/changelogs.rs, src/cli/mod.rs, src/release/check.rs
After ISOs are released, and we're ready to unleash desktop notifications for release upgrades.
=> feat: Unleash the 20.10 horde

gtk/src/events/background/mod.rs, gtk/src/events/mod.rs, gtk/src/lib.rs
=> feat(gtk): Show loading animation while checking for updates

src/release/repos.rs
=> fix: Also back up sources files

Cargo.lock, Cargo.toml, src/gnome_extensions.rs, src/misc.rs
=> fix: Move user extensions to extensions.bak on upgrade

Cargo.lock, Cargo.toml, changelogs/21.04, gtk/Cargo.toml, gtk/ffi/Cargo.toml, src/changelogs.rs, src/release/check.rs
=> feat: Enable Hirsute Release

Cargo.lock, Cargo.toml
=> fix: Update systemd-boot-conf dependency to fix error about missing linux field

i18n/nl/pop_upgrade_gtk.ftl
=> i18n(nl): Added Dutch translation

data/pop-upgrade.sh
=> fix: Nudge apt to ensure that libc++1 is upgraded to latest version

i18n/de/pop_upgrade_gtk.ftl
Here is my translation. I double checked, everything should be good.
=> i18n(de): Add german translation

i18n/ja/pop_upgrade_gtk.ftl
=> i18n(ja) : add Japanese translation

i18n/es/pop_upgrade_gtk.ftl, i18n/pt_BR/pop_upgrade_gtk.ftl
Adding Spanish translation and fixing a small mistake in the Portuguese translation
=> i18n(es): Add Spanish translation

data/do-release-upgrade, debian/control, debian/ubuntu-release-upgrader-core.install
=> feat: Replace do-release-upgrade

debian/control
=> fix(debian): Replace update-notifier and ubuntu-release-upgrader packages

changelogs/21.10, src/changelogs.rs, src/daemon/mod.rs, src/release/check.rs
Merge only when ready to release Impish.
=> feat: Impish release

changelogs/21.10
relase upgrades -> release upgrades
=> fix probable typo

src/release/mod.rs, src/release/repos.rs, src/repair/mod.rs, src/repair/packaging.rs
If there are `.save` files to restore from.
Closes #193
=> fix(restore): Remove impish sources when cancelling on hirsute or focal

changelogs/22.04, src/changelogs.rs
This PR adds the "22.04" change log.
=> 22.04 release notes

data/pop-upgrade.sh
This is intended to fix https://github.com/pop-os/upgrade/issues/265, and make the messages shown during upgrade slightly more consistent/more cleanly formatted.
=> Clean up Plymouth messages

changelogs/22.04
Corrected spelling when referring to Nix packages
=> *nix to Nix

i18n/cs/pop_upgrade_gtk.ftl
Hello, I have added a Czech translation according to the instructions found here: 
https://www.reddit.com/r/pop_os/comments/nb2rly/list_of_translatable_pop_os_projects/
In Czech update and upgrade are the same word, so I hope that won't cause confusion.
=> i18n(cs): Add Czech translation

i18n/pl/pop_upgrade_gtk.ftl
Hello, i have translated to Polish language
=> Added Polish Language

i18n/sv/pop_upgrade_gtk.ftl
=> Create pop_upgrade_gtk.ftl (SV)
