pop-os/upgrade

gtk/src/widgets/upgrade_option.rs

Prevents the bar from getting T H I C C C when there isn't a
widget above it.

Make the progressbar Valign be GTK_ALIGN_END instead of .._FILL.

---

Cargo.lock
gtk/Cargo.toml
gtk/src/errors.rs
gtk/src/events.rs
gtk/src/lib.rs
gtk/src/main.rs
gtk/src/widgets/dialogs/upgrade.rs
gtk/src/widgets/upgrade_option.rs
src/cli/mod.rs
src/client/mod.rs
src/daemon/methods.rs
src/daemon/mod.rs
src/release/mod.rs

Includes the last remaining changes before we release the integration of the GTK widget in GNOME Control Center. The previous PR had to be merged so that our CI would build GCC with the new C headers.

Upgrade GTK Widget (continued)

---

src/release/mod.rs

An error in the snapd function caused the source list to remain updated to the new release, later causing a live upgrade to be performed.
This change will wrap all code after the source list changes which may error into a closure. Any error returned from this closure will cause the rollback function to be called to revert the changes.

fix(daemon): Revert source list on any error after updating source lists

---

changelogs/18.10
changelogs/19.04
changelogs/19.10
src/changelogs.rs

I created changelogs based on the content provided in System76 blog posts from release.
https://blog.system76.com/post/184281497363/popos-1904-is-here
https://blog.system76.com/post/179217201328/see-what-changes-have-been-orbiting-popos
This pr resolves https://github.com/pop-os/upgrade/issues/55

Add changelogs for 19.04 and 18.10

---

Cargo.lock
gtk/Cargo.toml
gtk/src/main.rs

Our `ubuntu-version` crate set a day value of `0` for Focal's release date. The crate has been pointed to update this to the correct value of `23`. A day value of `0` caused a panic when converting it into a `Date<Utc>`, as `0` is considered to be invalid.

Fix EOL date panic in Focal

---

src/cli/mod.rs

Addresses a usability issue discussed further in #98 and #99 by outputting current, next, and available to STDOUT on every invocation of `upgrade`.
Closes #98

feat(cli) upgrade: output current, next, available

---

src/release/mod.rs

This is just a simple typo fix that I found in someone's logs:
Jul 22 12:02:11 pop-os pop-upgrade[25184]: [INFO ] pop_upgrade src/release/mod.rs:475: updated the package lists for the new relaese

changes relaese to release

---

gtk/src/events/mod.rs

This lets the customer know to send us the command output in their support ticket to provide as much information as possible in their first message to us.

update message about sending the output to support

---

debian/control

Using `shlibs` to generate the run-time library dependencies is the correct method in Debian packaging conventions, and is effective at determining what dependencies and versions are needed.

fix: Correctly use shlibs for dependencies

---

Cargo.toml
debian/changelog
debian/libpop-upgrade-gtk.shlibs
gtk/Cargo.toml
gtk/ffi/Cargo.toml

It seems the gnome-control-center binary ends up linking against the SONAME symlink, so it should depend on a version that includes it. With this, `dh_shlibdeps` generates such a dependency. This, or `.symbols`, is also required by the debian policy manual, so it's probably best to tend to follow the conventions for `.deb` packages.
This should not change the behavior of anything other than new packages built against this library.
Building the 3.38.2 branch of gnome-control-center with `fakeroot make -f debian/rules binary` when this version is installed resulted in a generated dependency with the version requirement from `.shlibs`.

fix: Add .shlibs file, and update version to 0.1.1

---

Cargo.lock
gtk/ffi/Cargo.toml
gtk/ffi/src/lib.rs

This will fix the locale defaulting to `en` in the widget from C.

fix(ffi): Initialize fluent locale on widget create

---

src/main.rs

fix: Prevent pop-upgrade service from running in an install environment

---

Cargo.lock
Cargo.toml
gtk/Cargo.toml

In zbus, this is fixed upstream in https://gitlab.freedesktop.org/dbus/zbus/-/merge_requests/254, but that is not in a stable release, and the betas including it have a semver bump and higher Rustc requirement.
Patching zbus would also work, but since the `dbus` create is already a dependency, this seems reasonable if it works alright.
Fix for https://github.com/pop-os/pop/issues/1792.

fix: Use dbus-rs backend of notify-rust to fix busy loop issue

---

Makefile
debian/libpop-upgrade-gtk.shlibs

The soname version has changed since the version in `Cargo.toml` was changed to 1.0.0.
This fixes an error in `dh_shlibdeps` on my Gnome 40 branch of gnome-control-center.

fix(shlibs): Update version to 1

---

gtk/src/events/mod.rs

an interior-mutable object shouldn't be declared as `const`
see [this reference](https://rust-lang.github.io/rust-clippy/v0.0.212/#declare_interior_mutable_const)
> Consts are copied everywhere they are referenced, i.e. every time you refer to the const a fresh instance of the Cell or Mutex or AtomicXxxx will be created, which defeats the whole purpose of using these types in the first place. The const should better be replaced by a static item if a global variable is wanted, or replaced by a const fn if a constructor is wanted.
> 
> Example
> ```rust
> use std::sync::atomic::{Ordering::SeqCst, AtomicUsize};
> 
> // Bad.
> const CONST_ATOM: AtomicUsize = AtomicUsize::new(12);
> CONST_ATOM.store(6, SeqCst);             // the content of the atomic is unchanged
> …
```

change global object from 'const' to 'static'

---

data/pop-upgrade.sh

fix: Add libselinux1:i386 to prerequisites if installed

---

Cargo.lock
daemon/src/release/check.rs
daemon/src/release/mod.rs
gtk/Cargo.toml
gtk/src/events/mod.rs
gtk/src/widgets/dialogs/mod.rs

- Relies on upgrade branch at https://github.com/pop-os/system-updater/pull/6
- Unholds all packages that might be held before setting up a release upgrade
- Removes two potentially-problematic packages (update-notifier-common and nodejs)
- Performs an autoremove when removing packages
- Holds snap packages after fetching
- 2 concurrent package fetches with 0ms delay between requests
- GTK panel is scrollable with https://github.com/pop-os/gnome-control-center/pull/227

Deferred Improvements

---

Cargo.lock
debian/control
gtk/Cargo.toml
gtk/build.rs
gtk/src/lib.rs

Relies on `libpop-system-updater-gtk-dev` from https://github.com/pop-os/system-updater/pull/9

feat: Link to pop-system-updater-gtk as a dylib

---

daemon/src/release/mod.rs

This definitely needs an engineering review (I wasn't sure what the best way to do this would be), but I've tested and confirmed that this does fix #337.
Testing checklist:
- Used to fail, now works.
- `Package 'epapirus-icon-theme' is not installed, so not removed` is now logged; no adverse effects.
- ~~[ ] Runs successfully if `epapirus-icon-theme` is installed but `papirus-icon-theme` is not~~
- Not a possible configuration; `epapirus-icon-theme` hard-depends on `papirus-icon-theme`. (If it were possible, `epapirus-icon-theme` may get removed anyway because it'd be orphaned after removing its PPA, but if it wasn't removed, it still shouldn't cause any problems since `papirus-icon-theme` wouldn't be upgraded on top of it in a scenario where it wasn't already installed by this point in …

fix: Remove epapirus before downgrading papirus

---

daemon/src/release/repos.rs

This mirror does not currently have aarch64 packages, so use `ports.ubuntu.com` again.

Don't attempt to use `apt.pop-os.org/ubuntu` on aarch64

---

daemon/src/release/mod.rs

There may be other safe packages that we could add here.
Closes #347

fix: add exemption for sentinelagent package

---

i18n/bn/pop_upgrade_gtk.ftl
i18n/cs/pop_upgrade_gtk.ftl
i18n/da/pop_upgrade_gtk.ftl
i18n/de/pop_upgrade_gtk.ftl
i18n/en/pop_upgrade_gtk.ftl
i18n/es/pop_upgrade_gtk.ftl
i18n/fr/pop_upgrade_gtk.ftl
i18n/hu/pop_upgrade_gtk.ftl
i18n/ja/pop_upgrade_gtk.ftl
i18n/nb-NO/pop_upgrade_gtk.ftl
i18n/nl/pop_upgrade_gtk.ftl
i18n/pl/pop_upgrade_gtk.ftl
i18n/pt-BR/pop_upgrade_gtk.ftl
i18n/ru/pop_upgrade_gtk.ftl
i18n/sl/pop_upgrade_gtk.ftl
i18n/sr/pop_upgrade_gtk.ftl
i18n/tr/pop_upgrade_gtk.ftl
i18n/uk/pop_upgrade_gtk.ftl
i18n/zh-CN/pop_upgrade_gtk.ftl

This fixes #181. Before:
After:
It does also add the exclamation mark on the main Upgrade page when a new version's available, which seems fine. The alternative would be separating them out into different strings.
I'm not an expert on punctuation across languages, but it seems better to add it to everything than to leave some of the languages missing a separator between the sentences. I'm expecting we'll get follow-up PRs from translators if there are any languages where an exclamation mark can't be used like this.

fix: Add missing punctuation to string

---

daemon/src/repair/misc.rs

Fixes https://github.com/pop-os/upgrade/issues/322.
Performed three tests:

fix: Handle PulseAudio path as file or directory
